com::placesandplaces::MainActivity
Button com.placesandplaces.MainActivity.btnFindIt
Referenced by com.placesandplaces.MainActivity::onCreate.
ArrayList<String> com.placesandplaces.MainActivity.resultList
Referenced by com.placesandplaces.MainActivity::autocomplete.
Bitmap com.placesandplaces.MainActivity.bmScreen
View com.placesandplaces.MainActivity.screen
EditText com.placesandplaces.MainActivity.EditTextIn
int com.placesandplaces.MainActivity.icount1
Referenced by com.placesandplaces.MainActivity::addTextView.
int com.placesandplaces.MainActivity.textViewCount
int com.placesandplaces.MainActivity.i
Referenced by com.placesandplaces.MainActivity::autocomplete, com.placesandplaces.MainActivity::onCreate.
EditText [] com.placesandplaces.MainActivity.et
Referenced by com.placesandplaces.MainActivity::addTextView, com.placesandplaces.MainActivity::onCreate.
String [] com.placesandplaces.MainActivity.stringArray
String com.placesandplaces.MainActivity.strPlaces1
String com.placesandplaces.MainActivity.strPlaces2
TextView com.placesandplaces.MainActivity.mOutput
Referenced by com.placesandplaces.MainActivity::onCreate.
TextView com.placesandplaces.MainActivity.mOutput2
Referenced by com.placesandplaces.MainActivity::onCreate.
String com.placesandplaces.MainActivity.KEY_INFORMATION
String com.placesandplaces.MainActivity.KEY_REFERENCE
String com.placesandplaces.MainActivity.KEY_NAME
String com.placesandplaces.MainActivity.KEY_VICINITY
Globals com.placesandplaces.MainActivity.g
Referenced by com.placesandplaces.MainActivity::addTextView, com.placesandplaces.MainActivity::onCreate, com.placesandplaces.MainActivity::setTextMethod.
MainActivity com.placesandplaces.MainActivity.ma
EditText com.placesandplaces.MainActivity.firstPlace
Referenced by com.placesandplaces.MainActivity::onCreate.
EditText com.placesandplaces.MainActivity.secondPlace
Referenced by com.placesandplaces.MainActivity::onCreate.
AlertDialog.Builder com.placesandplaces.MainActivity.screenDialog
Referenced by com.placesandplaces.MainActivity::OpenScreenDialog.
final String com.placesandplaces.MainActivity.PLACES_API_BASE
Referenced by com.placesandplaces.MainActivity::autocomplete.
final String com.placesandplaces.MainActivity.TYPE_AUTOCOMPLETE
Referenced by com.placesandplaces.MainActivity::autocomplete.
final String com.placesandplaces.MainActivity.OUT_JSON
Referenced by com.placesandplaces.MainActivity::autocomplete.
final String com.placesandplaces.MainActivity.RPC_QUEUE_NAME
Connection com.placesandplaces.MainActivity.connection
Referenced by com.placesandplaces.MainActivity::close, com.placesandplaces.MainActivity::onCreate.
Channel com.placesandplaces.MainActivity.channel
Referenced by com.placesandplaces.MainActivity::call, com.placesandplaces.MainActivity::onCreate.
String com.placesandplaces.MainActivity.requestQueueName
Referenced by com.placesandplaces.MainActivity::call.
String com.placesandplaces.MainActivity.replyQueueName
Referenced by com.placesandplaces.MainActivity::call, com.placesandplaces.MainActivity::onCreate.
QueueingConsumer com.placesandplaces.MainActivity.consumer
Referenced by com.placesandplaces.MainActivity::call, com.placesandplaces.MainActivity::onCreate.
void com.placesandplaces.MainActivity.onCreate(Bundle savedInstanceState)
References com.placesandplaces.MainActivity::addTextView, com.placesandplaces.MainActivity::btnFindIt, com.placesandplaces.Globals::buttonPushCount, com.placesandplaces.MainActivity::call, com.placesandplaces.MainActivity::channel, com.placesandplaces.MainActivity::connection, com.placesandplaces.MainActivity::consumer, com.placesandplaces.MainActivity::et, com.placesandplaces.MainActivity::firstPlace, com.placesandplaces.MainActivity::g, com.placesandplaces.MainActivity::i, com.placesandplaces.MainActivity::mOutput, com.placesandplaces.MainActivity::mOutput2, com.placesandplaces.MainActivity::replyQueueName, com.placesandplaces.MainActivity::secondPlace, com.placesandplaces.Globals::setLocation1, com.placesandplaces.Globals::setLocation2, com.placesandplaces.MainActivity::SetLocations, com.placesandplaces.MainActivity::setTextMethod.
String com.placesandplaces.MainActivity.call(String message)
References com.placesandplaces.MainActivity::channel, com.placesandplaces.MainActivity::consumer, com.placesandplaces.MainActivity::replyQueueName, com.placesandplaces.MainActivity::requestQueueName.
Referenced by com.placesandplaces.MainActivity::onCreate.
void com.placesandplaces.MainActivity.close()
References com.placesandplaces.MainActivity::connection.
void com.placesandplaces.MainActivity.addTextView(RelativeLayout r1, int buttoncount)
References com.placesandplaces.MainActivity::et, com.placesandplaces.MainActivity::g, com.placesandplaces.MainActivity::icount1, com.placesandplaces.Globals::setLocationVari.
Referenced by com.placesandplaces.MainActivity::onCreate.
void com.placesandplaces.MainActivity.setTextMethod(String ivalue, int i)
References com.placesandplaces.MainActivity::g, com.placesandplaces.Globals::setLocationi.
Referenced by com.placesandplaces.MainActivity::onCreate.
void com.placesandplaces.MainActivity.SetLocations()
References com.placesandplaces.MainActivity::OpenScreenDialog.
Referenced by com.placesandplaces.MainActivity::onCreate.
void com.placesandplaces.MainActivity.OpenScreenDialog()
References com.placesandplaces.MainActivity::screenDialog.
Referenced by com.placesandplaces.MainActivity::SetLocations.
ArrayList<String> com.placesandplaces.MainActivity.autocomplete(String input)
References com.placesandplaces.MainActivity::i, com.placesandplaces.MainActivity::OUT_JSON, com.placesandplaces.MainActivity::PLACES_API_BASE, com.placesandplaces.MainActivity::resultList, com.placesandplaces.MainActivity::TYPE_AUTOCOMPLETE.