com::placesandplaces::Globals
Globals com.placesandplaces.Globals.instance
Referenced by com.placesandplaces.Globals::getInstance.
String com.placesandplaces.Globals.location1
String com.placesandplaces.Globals.location2
CharSequence com.placesandplaces.Globals.textKey1
int com.placesandplaces.Globals.counterVar
Referenced by com.placesandplaces.Globals::getCounterVar, com.placesandplaces.Globals::setLocationi.
int com.placesandplaces.Globals.buttonPushCount
Referenced by com.placesandplaces::SuppressLint.
int com.placesandplaces.Globals.nameCount
int com.placesandplaces.Globals.pushID
int com.placesandplaces.Globals.push
int com.placesandplaces.Globals.counterLocVar
Referenced by com.placesandplaces.Globals::getLocationVari, com.placesandplaces.Globals::setLocationVari.
String [] com.placesandplaces.Globals.location_i
Referenced by com.placesandplaces.Globals::getLocationi.
com.placesandplaces.Globals.Globals()
Referenced by com.placesandplaces.Globals::getInstance.
void com.placesandplaces.Globals.setLocation1(String d)
Referenced by com.placesandplaces.MainActivity::onCreate.
String com.placesandplaces.Globals.getLocation1()
Referenced by com.placesandplaces::SuppressLint.
void com.placesandplaces.Globals.setLocation2(String d)
Referenced by com.placesandplaces.MainActivity::onCreate.
String com.placesandplaces.Globals.getLocation2()
Referenced by com.placesandplaces::SuppressLint.
CharSequence com.placesandplaces.Globals.getTextKey1()
void com.placesandplaces.Globals.setTextKey1(CharSequence d)
void com.placesandplaces.Globals.setLocationVari()
References com.placesandplaces.Globals::counterLocVar.
Referenced by com.placesandplaces.MainActivity::addTextView.
int com.placesandplaces.Globals.getLocationVari()
References com.placesandplaces.Globals::counterLocVar.
Referenced by com.placesandplaces::SuppressLint.
void com.placesandplaces.Globals.setLocationi(String d, int i)
References com.placesandplaces.Globals::counterVar.
Referenced by com.placesandplaces.MainActivity::setTextMethod.
String com.placesandplaces.Globals.getLocationi(int i)
References com.placesandplaces.Globals::location_i.
Referenced by com.placesandplaces::SuppressLint.
void com.placesandplaces.Globals.setCounterVar(int i)
int com.placesandplaces.Globals.getCounterVar()
References com.placesandplaces.Globals::counterVar.
static synchronized Globals com.placesandplaces.Globals.getInstance()
References com.placesandplaces.Globals::Globals, com.placesandplaces.Globals::instance.